@startuml
left to right direction

package controller {
  usecase DatasetResource
  usecase DatasetMetadataResource
  artifact DatasetLocator
  package validation [
    InputValidationService
  ]
  package filter [
    UserAgentFilter 
  ]
}

package model {
  artifact DatasetMetadata
  artifact DatasetCoordinates
  stack DatasetType
  artifact CollectionMetadata
  node DatasetService
  node MetadataService
}

package "database" {
  node TransactionController
  node DatabaseTypedClient
}

package conversion {
  node CsvConversionService
  node JsonConversionService
  node RootConversionService
  node ConversionServiceOrchestrator
}

package fetch {
  rectangle "MetadataBuilderService<DatasetMetadata>" as mbsd #line.dashed 
  rectangle "MetadataBuilderService<CollectionMetadata>" as mbsc #line.dashed 
  rectangle UrlBuilderService #line.dashed
  node DownloadService
  node DatasetFetchService
}

database mongodb

:user: -[dashed]d---> DatasetResource : HTTP
:user: -[dashed]d---> DatasetMetadataResource : HTTP

DatasetResource -r---> DatasetService
DatasetMetadataResource -l---> MetadataService

DatasetService ----> DatabaseTypedClient
DatasetService ----> TransactionController
DatasetService ----> DatasetFetchService
DatasetService ----> ConversionServiceOrchestrator

MetadataService ----> DatabaseTypedClient

DatabaseTypedClient -r-> mongodb

DatasetFetchService --> DownloadService
DatasetFetchService --> mbsd
DatasetFetchService --> mbsc
DatasetFetchService --> UrlBuilderService

ConversionServiceOrchestrator --> CsvConversionService
ConversionServiceOrchestrator --> JsonConversionService
ConversionServiceOrchestrator --> RootConversionService

@enduml